[package]
name    = "radius-rust"
version = "0.2.0"
authors = ["MikhailMS <1488maiklm@gmail.com>"]
edition = "2018"

[dependencies]
mio         = { version = "0.7", features = ["os-poll", "udp"] }
rand        = "0.7.3"
rust-crypto = "0.2"
thiserror   = "1.0.20"
