[package]
name    = "radius-rust"
version = "0.1.0"
authors = ["MikhailMS <1488maiklm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log         = "0.4"
mio         = "0.6"
rand        = "0.7.3"
rust-crypto = "0.2"
